version: '3'
services:
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "8070:8000"
    volumes:
      - /docker/mkdocs:/docs
    stdin_open: true
    tty: true
    restart: unless-stopped