services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "ghcr.io/jokob-sk/netalertx-dev:latest" 
    image: "ghcr.io/jokob-sk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /docker/netalertx/config:/data/config
      - /docker/netalertx/db:/data/db
      # (optional) useful for debugging if you have issues setting up the container
      - /docker/netalertx/logs:/data/log
      # (API: OPTION 1) use for performance
      - type: tmpfs
        target: /data/api
      # (API: OPTION 2) use when debugging issues
      # -  local_path/api:/app/api
    environment:
      - TZ=America/Chicago
      - PORT=20211
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID
    read_only: true