version: "3.9"

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /docker/NGINX_Proxy_Manager/data:/data
      - /docker/NGINX_Proxy_Manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped