version: '3.8'

services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/rancher-data:/var/lib/rancher
    privileged: true

volumes:
  rancher-data: