version: '3.8'

services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/rancher-data:/var/lib/rancher
    privileged: true
    environment:
    - K3S_DATASTORE_ENDPOINT=etcd
   # Increase quota to 2GB or 4GB to stop the immediate pressure
    - K3S_ETCD_QUOTA_BYTES=2147483648

volumes:
  rancher-data: