version: "3.9"
services:
  unifi:
    image: jacobalberty/unifi:latest
    container_name: unifi-controller
    network_mode: host
    environment:
      - DEBUG=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/unifi:/config
    restart: unless-stopped